# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#   
#   cities = City.create([{ :name => 'Chicago' }, { :name => 'Copenhagen' }])
#   Major.create(:name => 'Daley', :city => cities.first)

# Seed Kanas
group_single = Group.create(:name => 'single')
Kana.create( :romaji => 'a', :char => 'あ', :group => group_single)
Kana.create( :romaji => 'i', :char => 'い', :group => group_single)
Kana.create( :romaji => 'u', :char => 'う', :group => group_single)
Kana.create( :romaji => 'e', :char => 'え', :group => group_single)
Kana.create( :romaji => 'o', :char => 'お', :group => group_single)

group_k = Group.create(:name => 'k')
Kana.create( :romaji => 'ka', :char => 'か', :group => group_k)
Kana.create( :romaji => 'ki', :char => 'き', :group => group_k)
Kana.create( :romaji => 'ku', :char => 'く', :group => group_k)
Kana.create( :romaji => 'ke', :char => 'け', :group => group_k)
Kana.create( :romaji => 'ko', :char => 'こ', :group => group_k)

group_k_digraph = Group.create(:name => 'k digraph')
Kana.create( :romaji => 'kwa', :char => 'くゎ', :group => group_k_digraph)
Kana.create( :romaji => 'kya', :char => 'きゃ', :group => group_k_digraph)
Kana.create( :romaji => 'kyu', :char => 'きゅ', :group => group_k_digraph)
Kana.create( :romaji => 'kyo', :char => 'きょ', :group => group_k_digraph)

group = Group.create(:name => 's')
Kana.create( :romaji => 'sa', :char => 'さ', :group => group)
Kana.create( :romaji => 'shi', :char => 'し', :group => group)
Kana.create( :romaji => 'su', :char => 'す', :group => group)
Kana.create( :romaji => 'se', :char => 'せ', :group => group)
Kana.create( :romaji => 'so', :char => 'そ', :group => group)

group = Group.create(:name => 's digraph')
Kana.create( :romaji => 'sha', :char => 'しゃ', :group => group)
Kana.create( :romaji => 'shu', :char => 'しゅ', :group => group)
Kana.create( :romaji => 'sho', :char => 'しょ', :group => group)

group = Group.create(:name => 't')
Kana.create( :romaji => 'ta', :char => 'た', :group => group)
Kana.create( :romaji => 'chi', :char => 'ち', :group => group)
Kana.create( :romaji => 'tsu', :char => 'つ', :group => group)
Kana.create( :romaji => 'te', :char => 'て', :group => group)
Kana.create( :romaji => 'to', :char => 'と', :group => group)

group = Group.create(:name => 't digraph')
Kana.create( :romaji => 'cha', :char => 'ちゃ' , :group => group)
Kana.create( :romaji => 'chu', :char => 'ちゅ' , :group => group)
Kana.create( :romaji => 'cho', :char => 'ちょ' , :group => group)

group = Group.create(:name => 'n')
Kana.create( :romaji => 'na', :char => 'な' , :group => group)
Kana.create( :romaji => 'ni', :char => 'に' , :group => group)
Kana.create( :romaji => 'nu', :char => 'ぬ' , :group => group)
Kana.create( :romaji => 'ne', :char => 'ね' , :group => group)
Kana.create( :romaji => 'no', :char => 'の' , :group => group)

group = Group.create(:name => 'n digraph')
Kana.create( :romaji => 'nya', :char => 'にゃ' , :group => group)
Kana.create( :romaji => 'nyu', :char => 'にゅ' , :group => group)
Kana.create( :romaji => 'nyo', :char => 'にょ' , :group => group)

group = Group.create(:name => 'h')
Kana.create( :romaji => 'ha', :char => 'は' , :group => group)
Kana.create( :romaji => 'hi', :char => 'ひ' , :group => group)
Kana.create( :romaji => 'fu', :char => 'ふ' , :group => group)
Kana.create( :romaji => 'he', :char => 'へ' , :group => group)
Kana.create( :romaji => 'ho', :char => 'ほ' , :group => group)

group = Group.create(:name => 'h digraph')
Kana.create( :romaji => 'hya', :char => 'ひゃ' , :group => group)
Kana.create( :romaji => 'hyu', :char => 'ひゅ' , :group => group)
Kana.create( :romaji => 'hyo', :char => 'ひょ' , :group => group)

group = Group.create(:name => 'm')
Kana.create( :romaji => 'ma', :char => 'ま' , :group => group)
Kana.create( :romaji => 'mi', :char => 'み' , :group => group)
Kana.create( :romaji => 'mu', :char => 'む' , :group => group)
Kana.create( :romaji => 'me', :char => 'め' , :group => group)
Kana.create( :romaji => 'mo', :char => 'も' , :group => group)

group = Group.create(:name => 'm digraph')
Kana.create( :romaji => 'mya', :char => 'みゃ' , :group => group)
Kana.create( :romaji => 'myu', :char => 'みゅ' , :group => group)
Kana.create( :romaji => 'myo', :char => 'みょ' , :group => group)

group = Group.create(:name => 'y')
Kana.create( :romaji => 'ya', :char => 'や' , :group => group)
Kana.create( :romaji => 'yu', :char => 'ゆ' , :group => group)
Kana.create( :romaji => 'yo', :char => 'よ' , :group => group)

group = Group.create(:name => 'r')
Kana.create( :romaji => 'ra', :char => 'ら' , :group => group)
Kana.create( :romaji => 'ri', :char => 'り' , :group => group)
Kana.create( :romaji => 'ru', :char => 'る' , :group => group)
Kana.create( :romaji => 're', :char => 'れ' , :group => group)
Kana.create( :romaji => 'ro', :char => 'ろ' , :group => group)

group = Group.create(:name => 'r digraph')
Kana.create( :romaji => 'rya', :char => 'りゃ' , :group => group)
Kana.create( :romaji => 'ryu', :char => 'りゅ' , :group => group)
Kana.create( :romaji => 'ryo', :char => 'りょ' , :group => group)

group = Group.create(:name => 'w')
Kana.create( :romaji => 'wa', :char => 'わ' , :group => group)
Kana.create( :romaji => 'wi', :char => 'ゐ' , :group => group)
Kana.create( :romaji => 'we', :char => 'ゑ' , :group => group)
Kana.create( :romaji => 'wo', :char => 'を' , :group => group)

group = Group.create(:name => '*')
Kana.create( :romaji => 'n', :char => 'ん' , :group => group)
#Kana.create( :romaji => '(reduplicates', :char => 'ゝ' , :group => group)
#Kana.create( :romaji => '(reduplicates and', :char => 'ゞ' , :group => group)

group = Group.create(:name => 'g')
Kana.create( :romaji => 'ga', :char => 'が' , :group => group)
Kana.create( :romaji => 'gi', :char => 'ぎ' , :group => group)
Kana.create( :romaji => 'gu', :char => 'ぐ' , :group => group)
Kana.create( :romaji => 'ge', :char => 'げ' , :group => group)
Kana.create( :romaji => 'go', :char => 'ご' , :group => group)

group = Group.create(:name => 'g digraph')
Kana.create( :romaji => 'gwa', :char => 'ぐゎ' , :group => group)
Kana.create( :romaji => 'gya', :char => 'ぎゃ' , :group => group)
Kana.create( :romaji => 'gyu', :char => 'ぎゅ' , :group => group)
Kana.create( :romaji => 'gyo', :char => 'ぎょ' , :group => group)

group = Group.create(:name => 'z')
Kana.create( :romaji => 'za', :char => 'ざ' , :group => group)
Kana.create( :romaji => 'ji', :char => 'じ' , :group => group)
Kana.create( :romaji => 'zu', :char => 'ず' , :group => group)
Kana.create( :romaji => 'ze', :char => 'ぜ' , :group => group)
Kana.create( :romaji => 'zo', :char => 'ぞ' , :group => group)

group = Group.create(:name => 'z digraph')
Kana.create( :romaji => 'ja', :char => 'じゃ' , :group => group)
Kana.create( :romaji => 'ju', :char => 'じゅ' , :group => group)
Kana.create( :romaji => 'jo', :char => 'じょ' , :group => group)

group = Group.create(:name => 'd')
Kana.create( :romaji => 'da', :char => 'だ' , :group => group)
Kana.create( :romaji => 'ji', :char => 'ぢ' , :group => group)
Kana.create( :romaji => 'zu', :char => 'づ' , :group => group)
Kana.create( :romaji => 'de', :char => 'で' , :group => group)
Kana.create( :romaji => 'do', :char => 'ど' , :group => group)

group = Group.create(:name => 'd digraphs')
Kana.create( :romaji => 'ja', :char => 'ぢゃ' , :group => group)
Kana.create( :romaji => 'ju', :char => 'ぢゅ' , :group => group)
Kana.create( :romaji => 'jo', :char => 'ぢょ' , :group => group)

group = Group.create(:name => 'b')
Kana.create( :romaji => 'ba', :char => 'ば' , :group => group)
Kana.create( :romaji => 'bi', :char => 'び' , :group => group)
Kana.create( :romaji => 'bu', :char => 'ぶ' , :group => group)
Kana.create( :romaji => 'be', :char => 'べ' , :group => group)
Kana.create( :romaji => 'bo', :char => 'ぼ' , :group => group)

group = Group.create(:name => 'b digraphs')
Kana.create( :romaji => 'bya', :char => 'びゃ' , :group => group)
Kana.create( :romaji => 'byu', :char => 'びゅ' , :group => group)
Kana.create( :romaji => 'byo', :char => 'びょ' , :group => group)

group = Group.create(:name => 'p')
Kana.create( :romaji => 'pa', :char => 'ぱ' , :group => group)
Kana.create( :romaji => 'pi', :char => 'ぴ' , :group => group)
Kana.create( :romaji => 'pu', :char => 'ぷ' , :group => group)
Kana.create( :romaji => 'pe', :char => 'ぺ' , :group => group)
Kana.create( :romaji => 'po', :char => 'ぽ' , :group => group)

group = Group.create(:name => 'p digraphs')
Kana.create( :romaji => 'pya', :char => 'ぴゃ' , :group => group)
Kana.create( :romaji => 'pyu', :char => 'ぴゅ' , :group => group)
Kana.create( :romaji => 'pyo', :char => 'ぴょ' , :group => group)

group = Group.create(:name => 'v')
Kana.create( :romaji => 'vu', :char => 'ゔ' , :group => group)
